// Starter task library seeded onto every new course at signup, modeled on
// Conley CC's real day-to-day maintenance task list. Course owners edit/add
// from here — this just saves them from starting with an empty Task Library.
export const DEFAULT_TASK_LIBRARY: Array<{
  category: string;
  icon: string;
  name: string;
  frequency: string;
  estimated_duration: string;
  equipment: string;
  materials: string;
  description: string;
}> = [
  {
    category: "Mowing",
    icon: "🌱",
    name: "Mow Greens",
    frequency: "Daily",
    estimated_duration: "45 min",
    equipment: "Greens mower",
    materials: "",
    description: "Mowed daily to maintain putting surface speed and consistency.",
  },
  {
    category: "Mowing",
    icon: "🌱",
    name: "Mow Tees",
    frequency: "2x/week",
    estimated_duration: "30 min",
    equipment: "Tee mower",
    materials: "",
    description: "Mowed at least twice weekly to maintain tee box height.",
  },
  {
    category: "Mowing",
    icon: "🌾",
    name: "Mow Fairways",
    frequency: "3-4x/week",
    estimated_duration: "90 min",
    equipment: "Fairway mower",
    materials: "",
    description: "Mowed 3-4 times per week during peak growing season.",
  },
  {
    category: "Mowing",
    icon: "🌾",
    name: "Mow Rough",
    frequency: "Weekly",
    estimated_duration: "120 min",
    equipment: "Rough mower",
    materials: "",
    description: "Cut on a weekly rotation, more often in high growth periods.",
  },
  {
    category: "Bunkers",
    icon: "🏖️",
    name: "Hand Rake Bunker Faces",
    frequency: "Daily",
    estimated_duration: "30 min",
    equipment: "Hand rake",
    materials: "",
    description: "Steep faces and perimeters hand-raked where machines can't reach.",
  },
  {
    category: "Bunkers",
    icon: "🏖️",
    name: "Rake Bunkers (Machine)",
    frequency: "Daily",
    estimated_duration: "60 min",
    equipment: "Bunker rake machine",
    materials: "",
    description: "Machine-raked flat areas each morning before play.",
  },
  {
    category: "Bunkers",
    icon: "🏖️",
    name: "Edge Bunkers",
    frequency: "Weekly",
    estimated_duration: "45 min",
    equipment: "Bunker edger",
    materials: "",
    description: "Trim turf edges to keep clean bunker lines.",
  },
  {
    category: "Course Setup",
    icon: "🚩",
    name: "Move Tee Markers",
    frequency: "Daily",
    estimated_duration: "15 min",
    equipment: "",
    materials: "",
    description: "Rotate tee marker placement to distribute wear.",
  },
  {
    category: "Course Setup",
    icon: "⛳",
    name: "Cup Cutting / Hole Change",
    frequency: "Daily",
    estimated_duration: "30 min",
    equipment: "Cup cutter, hole cutter",
    materials: "",
    description: "New hole locations set each morning per rotation plan.",
  },
  {
    category: "Course Setup",
    icon: "🩹",
    name: "Divot Filling & Ball Mark Repair",
    frequency: "Daily",
    estimated_duration: "30 min",
    equipment: "",
    materials: "Sand/seed mix",
    description: "Fill fairway divots and repair greens ball marks.",
  },
  {
    category: "Cultural Practices",
    icon: "🌀",
    name: "Core Aerification",
    frequency: "Seasonal",
    estimated_duration: "4 hrs",
    equipment: "Aerifier",
    materials: "",
    description: "Relieves compaction and improves air/water/nutrient flow to roots.",
  },
  {
    category: "Cultural Practices",
    icon: "✂️",
    name: "Verticutting",
    frequency: "Bi-weekly",
    estimated_duration: "90 min",
    equipment: "Verticutter",
    materials: "",
    description: "Thins thatch buildup; best done during active turf growth.",
  },
  {
    category: "Cultural Practices",
    icon: "🏜️",
    name: "Topdressing",
    frequency: "Monthly",
    estimated_duration: "2 hrs",
    equipment: "Topdresser",
    materials: "Sand",
    description: "Smooths surface and speeds recovery after cultural practices.",
  },
  {
    category: "Grounds",
    icon: "🍂",
    name: "Blow Debris / Leaf Removal",
    frequency: "Daily",
    estimated_duration: "60 min",
    equipment: "Blower",
    materials: "",
    description: "Clear clippings, leaves, and debris from greens and fairways.",
  },
  {
    category: "Irrigation",
    icon: "💦",
    name: "Irrigation Head Inspection",
    frequency: "Daily",
    estimated_duration: "30 min",
    equipment: "",
    materials: "",
    description: "Check for broken/misaligned heads and leaks across zones.",
  },
  {
    category: "Equipment",
    icon: "🔧",
    name: "End-of-Day Equipment Cleaning",
    frequency: "Daily",
    estimated_duration: "30 min",
    equipment: "",
    materials: "",
    description: "Wash down and inspect mowers/equipment after each use.",
  },
];
